[tool.poetry]
name = "plot"
version = "0.1.0"
description = ""
authors = ["davkk <dadulerk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.9.0"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
