#!/usr/bin/env python

import io
import sys

import numpy as np

data = io.StringIO(sys.stdin.read())
x, y = np.loadtxt(data).T

max_idx = np.argmax(y)
mask = np.isclose(y, y[max_idx], atol=0.01)

max_idx = np.argwhere(mask).flatten()[0]

print(x[max_idx])
