#!/usr/bin/env bash

k=${1:-"none"}
now=`date +%s`

parallel --lb \
    go run cmd/main.go -network=ba -n=10000 -m=2 -init=max -beta=0.1 -gamma=0.1 -k=$k \
    ::: {1..20} \
    | tee ${OUTPUT}/${k}/ba_infected_vs_step_$now \
    | python ${PLOT}/plot_infected_vs_step.py \
        --out ${FIGURES}/${k}/ba_infected_vs_step.pdf \
        --xlabel "krok symulacji \$t$" \
        --ylabel "procent populacji"
