#!/usr/bin/env bash

now=`date +%s`

parallel --lb \
    go run cmd/main.go -network=ba -n=1000 -m=2 -init={1} -beta={2} -gamma=0.1 \
        \| average_last_10 \
        \| awk \'{ print \"{1}\", \$0 }\' \
        ::: max min rnd \
        ::: `seq 0 0.005 0.1` \
        ::: {1..10} \
| average_by 0 1 \
| tee ${OUTPUT}/none/ba_max_min_rnd_$now \
| python ${PLOT}/plot_max_min_rnd.py \
    --out ${FIGURES}/none/ba_max_min_rnd.pdf \
    --xlabel "$\lambda$" \
    --ylabel "procent zarażonych \$i(t_{\max})$"
