#!/usr/bin/env bash

k=${1:-"none"}
max=${2:-0.03}
step=${3:-0.001}
now=`date +%s`

function run {
    for m in {2..12}; do
        >&2 echo "m =" $m

        parallel --lb \
            go run ./cmd/main.go -network=ba -n=1000 -m=$m -init=max -beta={1} -gamma=0.1 -k=$k \
            \| average_last_10 \
            ::: `seq 0 $step $max` \
            ::: {1..10} \
        | average_by 0 \
        | tee ${OUTPUT}/${k}/ba_infected_vs_ratio_m=${m} \
        | find_threshold \
        | awk "{ print 2 * $m, \$1 }"
    done
}

run \
| tee ${OUTPUT}/${k}/ba_threshold_vs_k_$now \
| python ${PLOT}/plot_x_vs_y.py \
    --out ${FIGURES}/${k}/ba_threshold_vs_k.pdf \
    --xlabel "średni stopień węzła $\langle k \rangle$" \
    --ylabel "próg epidemii $\lambda_c$"


