#!/usr/bin/env bash

k=${1:-"none"}
max=${2:-0.1}
step=${3:-0.01}
now=`date +%s`

parallel --lb \
    go run cmd/main.go -network=ba -n=10000 -m=2 -init=max -beta={1} -gamma=0.1 -k=$k \
    \| average_last_10 \
    ::: `seq 0 $step $max` \
    ::: {1..10} \
| average_by 0 \
| tee ${OUTPUT}/${k}/ba_infected_vs_ratio_$now \
| python ${PLOT}/plot_infected_vs_ratio.py \
    --out ${FIGURES}/${k}/ba_infected_vs_ratio.pdf \
    --xlabel "$\lambda$" \
    --ylabel "procent zarażonych \$i(t_{\max})$"
