#!/usr/bin/env bash

k=${1:-"none"}
max=${2:-0.03}
step=${3:-0.001}
now=`date +%s`

function run {
    for p in $(seq 0.001 0.001 0.02); do
        >&2 echo "p =" $p

        parallel --lb \
            go run ./cmd/main.go -network=er -n=1000 -p=$p -init=max -beta={1} -gamma=0.1 -k=$k \
            \| average_last_10 \
            ::: `seq 0 $step $max` \
            ::: {1..10} \
        | average_by 0 \
        | tee ${OUTPUT}/${k}/er_infected_vs_ratio_p=${p} \
        | find_threshold \
        | awk "{ print 1000 * $p, \$1 }"
    done
}

run \
| tee ${OUTPUT}/${k}/er_threshold_vs_k_$now \
| python ${PLOT}/plot_x_vs_y.py \
    --out ${FIGURES}/${k}/er_threshold_vs_k.pdf \
    --xlabel "średni stopień węzła $\langle k \rangle$" \
    --ylabel "próg epidemii $\lambda_c$"


